INSERT INTO `courses` (`course_code`, `title`, `description`, `credits`) VALUES
('CHEM103', 'General Chemistry I', 'Introductory general chemistry course focused on matter, chemical calculations, and foundational laboratory science concepts.', 4),
('CHEM113', 'General Chemistry II', 'Continuation of general chemistry covering kinetics, equilibria, electrochemistry, and chemistry of the elements.', 4),
('CHEM121', 'Chemistry in the Modern World', 'Survey of chemistry for non-science majors with emphasis on health, safety, the environment, and everyday decision-making.', 3),
('CHEM297', 'Environmental Chemistry', 'Applied chemistry course focused on chemical processes in natural systems and environmental impacts on air, water, and soil.', 3),
('CMSC100', 'Social Networking and Cybersecurity Best Practices', 'Hands-on introduction to social networking tools and personal cybersecurity practices for safe online collaboration.', 3),
('CMSC105', 'Introduction to Problem-Solving and Algorithm Design', 'Applied introduction to algorithmic thinking and programming problem solving using core programming constructs.', 3),
('CMSC115', 'Fundamentals of Programming and Software Development', 'Foundation course in programming and software development with emphasis on coding, debugging, and documentation.', 3),
('CMSC150', 'Introduction to Discrete Structures', 'Introduction to logic, sets, functions, relations, graphs, trees, and proof techniques used in computer science.', 3),
('CMSC215', 'Object Oriented Programming', 'Study of object-oriented software development using classes, inheritance, interfaces, and exception handling.', 3),
('CMSC220', 'Intermediate Programming', 'Intermediate programming course that strengthens software construction, testing, and object-oriented design skills.', 3),
('CMSC310', 'Computer Systems and Architecture', 'Study of computer architecture, data representation, assembly language, memory, and processor organization.', 3),
('CMSC315', 'Data Structures and Analysis', 'Project-driven study of lists, stacks, queues, trees, graphs, recursion, sorting, and algorithm analysis.', 3),
('CMSC320', 'Relational Database Concepts and Applications', 'Study of relational database design, normalization, SQL, and database implementation concepts.', 3),
('CMSC325', 'Game Design and Development', 'Project-based introduction to modern game design and development concepts, tools, and production workflows.', 3),
('CMSC330', 'Advanced Programming Languages', 'Comparative study of programming language design, syntax, semantics, and runtime behavior.', 3),
('CMSC335', 'Object-Oriented and Concurrent Programming', 'Applied study of modern Java programming with emphasis on concurrency, streams, and scalable software construction.', 3),
('CMSC340', 'Web Programming', 'Course on modern web application development covering HTTP, HTML, CSS, JavaScript, server-side design, and security.', 3),
('CMSC345', 'Software Engineering Principles and Techniques', 'Introduction to software engineering processes, planning, teamwork, quality, and development lifecycle practices.', 3),
('CMSC405', 'Computer Graphics', 'Hands-on introduction to computer graphics with 2D and 3D rendering, animation, and OpenGL-based programming.', 3),
('CMSC412', 'Operating Systems', 'Study of operating system fundamentals including processes, resources, memory management, and system design.', 3),
('CMSC415', 'Distributed Database Systems', 'Examination of distributed database architecture, distributed design, and related big data and NoSQL concepts.', 3),
('CMSC420', 'Advanced Relational Database Concepts and Applications', 'Advanced database course covering enterprise SQL, procedures, triggers, warehousing, and administration concepts.', 3),
('CMSC425', 'Mobile App Development', 'Study of Android mobile application design and development with emphasis on architecture, interfaces, and privacy.', 3),
('CMSC427', 'Artificial Intelligence Foundations', 'Introduction to artificial intelligence theory and practice, including search, knowledge representation, logic, and learning.', 3),
('CMSC430', 'Compiler Theory and Design', 'Study of language translation, parsing, grammars, and code generation in compiler construction.', 3),
('CMSC440', 'Advanced Programming in Java', 'Advanced full-stack and enterprise-style Java programming with emphasis on maintainable, secure web applications.', 3),
('CMSC451', 'Design and Analysis of Computer Algorithms', 'Study of algorithm design strategies, correctness, and asymptotic analysis for complex computational problems.', 3),
('CMSC465', 'Image and Signal Processing', 'Project-driven study of signal analysis, filtering, Fourier methods, image transformation, and classification.', 3),
('CMSC486A', 'Workplace Learning in Computer Science', 'Supervised workplace learning course integrating computer science study with guided professional experience.', 3),
('CMSC486B', 'Workplace Learning in Computer Science', 'Extended supervised workplace learning course integrating computer science study with guided professional experience.', 6),
('CMSC495', 'Computer Science Capstone', 'Capstone course focused on planning, building, testing, and documenting collaborative computer science projects.', 3),
('CMSC498', 'Special Topics in Computer Science', 'Seminar course covering selected advanced or emerging topics in computer science.', 3),
('ENGL102', 'Composition and Literature', 'Writing-intensive literature course focused on analysis, academic writing, and interpretation of literary texts.', 3),
('ENGL103', 'Introduction to Mythology', 'Survey of classical mythology and its continuing influence on literature, culture, and modern society.', 3),
('ENGL240', 'Introduction to Fiction, Poetry, and Drama', 'Introduction to literary genres with emphasis on close reading, interpretation, and analytical writing.', 3),
('ENGL250', 'Introduction to Women''s Literature', 'Survey of literature by and about women across cultures and historical periods.', 3),
('ENGL281', 'Standard English Grammar', 'Advanced study of standard edited English focused on grammar, clarity, and effective prose.', 3),
('ENGL294', 'Introduction to Creative Writing', 'Introductory creative writing course focused on drafting, revision, critique, and literary craft.', 3),
('ENGL303', 'Critical Approaches to Literature', 'Foundation course in literary criticism, close reading, and analytical writing.', 3),
('ENGL310', 'Renaissance Literature', 'Study of major British authors and texts from the English Renaissance.', 3),
('ENGL311', 'The Long 18th-Century British Literature', 'Study of major British authors and literary works from the Restoration through the Age of Sensibility.', 3),
('ENGL312', '19th-Century British Literature', 'Study of major British authors and works from the Romantic and Victorian periods.', 3),
('ENGL363', 'African American Authors from the Colonial Era to 1900', 'Study of African American authors before 1900 in literary and historical context.', 3),
('ENGL364', 'African American Authors from 1900 to Present', 'Study of modern and contemporary African American authors in historical and literary context.', 3),
('ENGL381', 'Special Topics in Creative Writing', 'Creative writing workshop course exploring selected genres, forms, and special writing topics.', 3),
('ENGL384', 'Advanced Grammar and Style', 'Advanced writing course focused on grammar, style, editing, rhetorical control, and polished prose.', 3),
('ENGL386', 'History of the English Language', 'Study of the development, structure, and continuing evolution of the English language.', 3),
('ENGL389', 'Writing Workshop', 'Workshop-based writing course centered on drafting, peer review, revision, and portfolio development.', 3),
('ENGL406', 'Shakespeare Studies', 'Intensive study of Shakespeare''s works in literary, historical, and cultural context.', 3),
('ENGL418', 'Major British Writers Before 1800', 'Focused study of major British writers before 1800 using historical and critical perspectives.', 3),
('ENGL430', 'Early American Literature', 'Survey of early American literature across key periods, movements, and historical developments.', 3),
('ENGL433', 'Modern American Literature', 'Study of modern American literature with emphasis on modernism, context, and critical interpretation.', 3),
('ENGL439', 'Major American Writers', 'Focused study of selected American writers and the historical and cultural influences on their work.', 3),
('ENGL441', 'Postmodern American Literature: 1945 to 1999', 'Study of post-1945 American literature through major themes, movements, and cultural change.', 3),
('ENGL459', 'Contemporary Global Literatures', 'Advanced study of contemporary global literature with attention to region, history, and social justice.', 3),
('ENGL495', 'English Literature Capstone', 'Capstone course integrating literary study, portfolio development, research, and advanced writing.', 3),
('HIST115', 'World History I', 'Survey of world history from prehistory to around 1500 with emphasis on civilizations and global development.', 3),
('HIST116', 'World History II', 'Survey of world history from around 1500 to the present with emphasis on global systems and transformations.', 3),
('HIST125', 'Technological Transformations', 'History course examining the reciprocal relationship between technology, society, and historical change.', 3),
('HIST141', 'Western Civilization I', 'Survey of Western civilization from antiquity through the Reformation.', 3),
('HIST142', 'Western Civilization II', 'Survey of Western civilization from the Reformation to the modern period.', 3),
('HIST156', 'History of the United States to 1865', 'Survey of United States history from colonization through the Civil War era.', 3),
('HIST157', 'History of the United States from 1865', 'Survey of United States history from Reconstruction to the present.', 3),
('HIST202', 'Principles of War', 'Study of classic principles of war and their influence on military and national security practice.', 3),
('HIST289', 'Historical Methods', 'Introduction to historical methods, approaches, ethics, and professional practice in the discipline.', 3),
('HIST309', 'Historical Writing', 'Advanced history course focused on research design, source evaluation, and historical writing.', 3),
('HIST316L', 'The American West', 'Study of the exploration, settlement, development, and mythology of the American West.', 3),
('HIST326', 'Ancient Rome', 'Study of ancient Rome and the development of Roman institutions, politics, and society.', 3),
('HIST337', 'Europe and the World', 'Analysis of Europe''s interaction with the wider world through empire, culture, and global change.', 3),
('HIST365', 'Modern America', 'Survey of modern United States history from the New Deal through the turn of the 21st century.', 3),
('HIST377', 'U.S. Women''s History: 1870 to 2000', 'Examination of the experiences of women in the United States from 1870 to 2000.', 3),
('HIST381', 'America in Vietnam', 'Historical examination of U.S. involvement in Vietnam and its political, military, and cultural legacy.', 3),
('HIST392', 'History of the Contemporary Middle East', 'Survey of the modern Middle East with emphasis on politics, nationalism, conflict, and global relations.', 3),
('HIST461', 'African American History: 1865 to the Present', 'Study of African American history from emancipation through the modern era.', 3),
('HIST462', 'The U.S. Civil War', 'In-depth examination of the origins, conduct, and consequences of the American Civil War.', 3),
('HIST464', 'World War I', 'Intensive study of the origins, conduct, and impact of the First World War.', 3),
('HIST465', 'World War II', 'Study of the causes, global conflict, and consequences of the Second World War.', 3),
('HIST480', 'History of China to 1912', 'Survey of Chinese history from early civilization through the end of the Qing dynasty.', 3),
('HIST482', 'History of Japan to 1800', 'Survey of Japanese history from its origins through the late Edo period.', 3),
('HIST483', 'History of Japan Since 1800', 'Survey of Japanese history from the modern era to the present.', 3),
('HIST486A', 'Workplace Learning in History', 'Supervised workplace learning course integrating history study with guided professional experience.', 3),
('HIST486B', 'Workplace Learning in History', 'Extended supervised workplace learning course integrating history study with guided professional experience.', 6),
('HIST495', 'History Capstone', 'Capstone research course focused on producing a substantial original historical project.', 3),
('IFSM201', 'Concepts and Applications of Information Technology', 'Introduction to information technology, data, software, hardware, networks, and responsible technology use.', 3),
('IFSM300', 'Information Systems in Organizations', 'Overview of how information systems support organizational goals, processes, and strategy.', 3),
('IFSM301', 'Foundations of Management Information Systems', 'Introduction to IT management, governance, strategic alignment, and decision-making in organizations.', 3),
('IFSM304', 'Ethics in Information Technology', 'Study of ethical decision-making and responsible practice in the use of information technology.', 3),
('IFSM305', 'Information Systems in Healthcare Organizations', 'Examination of how information systems support healthcare strategy, safety, quality, and operations.', 3),
('IFSM310', 'Software and Hardware Infrastructure Concepts', 'Study of computing infrastructure components and integrated systems that support business requirements.', 3),
('IFSM311', 'Enterprise Architecture', 'Study of enterprise architecture frameworks and the alignment of systems with organizational change.', 3),
('IFSM370', 'Telecommunications in Information Systems', 'Introduction to telecommunications, networking, and secure infrastructure planning for business systems.', 3),
('IFSM380', 'Managing and Leading in Information Technology', 'Leadership and management course for information technology professionals in fast-paced workplaces.', 3),
('IFSM432', 'Business Continuity Planning', 'Study of business continuity and disaster recovery planning for mission-critical information systems.', 3),
('IFSM438', 'Information Systems Project Management', 'Applied project management course focused on planning, control, and delivery of IT projects.', 3),
('IFSM441', 'Agile Project Management', 'Advanced study of agile project management methods for software and technology initiatives.', 3),
('IFSM461', 'Systems Analysis and Design', 'Project-driven course on translating business requirements into effective operational systems.', 3),
('IFSM486A', 'Workplace Learning in Management Information Systems', 'Supervised workplace learning course integrating management information systems study with professional experience.', 3),
('IFSM486B', 'Workplace Learning in Management Information Systems', 'Extended supervised workplace learning course integrating management information systems study with professional experience.', 6),
('IFSM495', 'Management Information Systems Capstone', 'Capstone course integrating analysis, planning, design, and problem solving in management information systems.', 3),
('MATH105', 'Topics for Mathematical Literacy', 'Mathematics course covering quantitative reasoning, modeling, finance, probability, and statistical thinking.', 3),
('MATH107', 'College Algebra', 'Study of equations, inequalities, functions, graphing, and mathematical modeling in algebra.', 3),
('MATH108', 'Trigonometry and Analytical Geometry', 'Continuation course in trigonometry, analytic geometry, vectors, sequences, and conic sections.', 3),
('MATH115', 'Pre-Calculus', 'Pre-calculus course emphasizing equations, functions, graphs, and mathematical modeling.', 3),
('MATH140', 'Calculus I', 'Introduction to differential and integral calculus with applications.', 4),
('MATH141', 'Calculus II', 'Continuation of calculus covering advanced integration techniques, sequences, and series.', 4),
('MATH241', 'Calculus III', 'Multivariable calculus course covering vectors, partial derivatives, and multiple integration.', 4),
('MATH246', 'Differential Equations', 'Introduction to ordinary differential equations and mathematical models for physical systems.', 3),
('MATH301', 'Concepts of Real Analysis I', 'Upper-level mathematics course focused on formal proof and real analysis concepts.', 3),
('MATH340', 'Linear Algebra', 'Study of vector spaces, matrices, linear transformations, eigenvalues, and applications.', 4),
('MATH402', 'Algebraic Structures', 'Upper-level abstract algebra course covering groups, rings, fields, and proof techniques.', 3),
('MATH463', 'Complex Analysis', 'Study of complex variables, mappings, integrals, series, and applications.', 3),
('NURS302', 'Transition to Professional Nursing Practice', 'Transition course for registered nurses focused on professional identity, inquiry, communication, and patient safety.', 3),
('NURS322', 'Health Assessment and Wellness Promotion', 'Nursing health assessment course focused on holistic assessment, wellness promotion, and chronic disease management.', 4),
('NURS352', 'Introduction to Nursing Scholarship', 'Study of research methods and scholarly inquiry to support evidence-based nursing practice.', 3),
('NURS372', 'Introduction to Healthcare Informatics Technology in Nursing', 'Nursing informatics course focused on communication technologies, documentation, and ethical use of health information systems.', 3),
('NURS392', 'Policy, Politics, and Economics in Healthcare', 'Study of healthcare policy, politics, economics, advocacy, and equity in nursing practice.', 3),
('NURS412', 'Population, Global, and Community Health Issues', 'Study of community, public, and global health nursing with emphasis on population-focused care.', 3),
('NURS432', 'Leadership in Personal and Professional Nursing Practice', 'Leadership course focused on communication, collaboration, management, and evidence-based nursing leadership.', 3),
('NURS452', 'Complex Healthcare Systems: Quality Improvement and Patient Safety', 'Study of quality improvement, patient safety, systems thinking, and evidence-based solutions in complex healthcare settings.', 3),
('NURS462', 'Nursing Care of the Family and Community', 'Community and family nursing course focused on population health, prevention, and care coordination across settings.', 4),
('NURS472', 'Nursing Practice Experience', 'Practice experience course synthesizing nursing theory, scholarship, leadership, and applied nursing skills.', 2),
('NURS496', 'Nursing Capstone', 'Writing-intensive capstone course focused on evidence-based nursing practice and quality improvement project design.', 3),
('PHYS121', 'Fundamentals of Physics I', 'Introductory physics course covering mechanics, motion, force, and energy.', 4),
('PHYS122', 'Fundamentals of Physics II', 'Continuation of introductory physics covering electricity, magnetism, waves, and related concepts.', 4);
