-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 18:23:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registrationdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registrationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registrationdb` DEFAULT CHARACTER SET utf8 ;
USE `registrationdb` ;

-- -----------------------------------------------------
-- Table `registrationdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`users` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_login` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`courses` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(10) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `credits` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_code_UNIQUE` (`course_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`semesters` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`semesters` (
  `semester_id` INT NOT NULL AUTO_INCREMENT,
  `term` VARCHAR(8) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`semester_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`professors` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`professors` (
  `user_id` INT NOT NULL,
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_professors_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`sections` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`sections` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `semester_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `capacity` INT NULL COMMENT 'NULL = no set capacity, Integer = capped enrollment',
  `days` VARCHAR(10) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  PRIMARY KEY (`section_id`),
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  INDEX `semester_id_idx` (`semester_id` ASC) VISIBLE,
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_sections_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_semester`
    FOREIGN KEY (`semester_id`)
    REFERENCES `registrationdb`.`semesters` (`semester_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_professor`
    FOREIGN KEY (`professor_id`)
    REFERENCES `registrationdb`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`students` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`students` (
  `user_id` INT NOT NULL,
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`enrollments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`enrollments` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`enrollments` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `status` ENUM('enrolled', 'dropped', 'completed', 'waitlisted') NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `section_id_idx` (`section_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_student_section` (`section_id` ASC, `student_id` ASC) VISIBLE,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_enrollments_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `registrationdb`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollments_section`
    FOREIGN KEY (`section_id`)
    REFERENCES `registrationdb`.`sections` (`section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`prerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`prerequisites` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`prerequisites` (
  `prerequisite_course_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`prerequisite_course_id`, `course_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_prereq_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prereq_required_course`
    FOREIGN KEY (`prerequisite_course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registrationdb`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`admins` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`admins` (
  `user_id` INT NOT NULL,
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `access_level` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
