INSERT INTO `users` (`name`, `email`, `password_hash`, `first_login`) VALUES
('Christian Horner', 'horne_chri87@gmail.com', '$2b$10$pIlyp3XEcmfU8DeWU2mrLOME78CJIdd2yhrChPSO0VC6q42KuaxgG', '0');

INSERT INTO `users` (`name`, `email`, `password_hash`) VALUES

('Toto Wolff', 'wolff_toto00@gmail.com', ''),
('James Vowles', 'vowle_jame00@gmail.com', ''),
('Zak Brown', 'brown_zak00@gmail.com', ''),

('Max Verstappen', 'verst_max1@gmail.com', ''),
('Sergio Perez', 'perez_serg11@gmail.com', ''),
('Lewis Hamilton', 'hamil_lewi44@gmail.com', ''),
('George Russell', 'russe_geor63@gmail.com', ''),
('Charles Leclerc', 'lecle_char16@gmail.com', ''),
('Carlos Sainz', 'sainz_carl55@gmail.com', ''),
('Lando Norris', 'norri_land4@gmail.com', ''),
('Oscar Piastri', 'piast_osca81@gmail.com', ''),
('Fernando Alonso', 'alons_fern14@gmail.com', ''),
('Lance Stroll', 'strol_lanc18@gmail.com', ''),
('Pierre Gasly', 'gasly_pierr10@gmail.com', ''),
('Esteban Ocon', 'ocon_este31@gmail.com', ''),
('Yuki Tsunoda', 'tsuno_yuki22@gmail.com', ''),
('Daniel Ricciardo', 'ricci_dani3@gmail.com', ''),
('Valtteri Bottas', 'botta_valt77@gmail.com', ''),
('Zhou Guanyu', 'zhou_guan24@gmail.com', ''),
('Kevin Magnussen', 'magnu_kevi20@gmail.com', ''),
('Nico Hulkenberg', 'hulke_nico27@gmail.com', ''),
('Alexander Albon', 'albon_alex23@gmail.com', ''),
('Logan Sargeant', 'sarge_loga2@gmail.com', ''),
('Nyck de Vries', 'devri_nyck21@gmail.com', ''),
('Liam Lawson', 'lawso_liam40@gmail.com', ''),
('Kimi Raikkonen', 'raikk_kimi7@gmail.com', ''),
('Sebastian Vettel', 'vette_seba5@gmail.com', ''),
('Jenson Button', 'butto_jens22@gmail.com', ''),
('Nico Rosberg', 'rosbe_nico6@gmail.com', ''),
('Felipe Massa', 'massa_feli19@gmail.com', ''),
('Rubens Barrichello', 'barri_rube11@gmail.com', ''),
('Michael Schumacher', 'schum_mich47@gmail.com', ''),
('Mick Schumacher', 'schum_mick47@gmail.com', ''),
('Romain Grosjean', 'grosj_roma8@gmail.com', ''),
('Pastor Maldonado', 'maldo_past18@gmail.com', ''),
('Ayrton Senna', 'senna_ayrt12@gmail.com', ''),
('Alain Prost', 'prost_alai1@gmail.com', ''),
('Niki Lauda', 'lauda_niki12@gmail.com', ''),
('Gerhard Berger', 'berge_gerh28@gmail.com', ''),
('David Coulthard', 'coult_davi2@gmail.com', ''),
('Mika Hakkinen', 'hakki_mika8@gmail.com', ''),
('Jacques Villeneuve', 'ville_jacq27@gmail.com', ''),
('Juan Pablo Montoya', 'monto_juan42@gmail.com', ''),
('Kimi Antonelli', 'anton_kimi12@gmail.com', ''),
('Oliver Bearman', 'bearm_oliv87@gmail.com', ''),
('Jack Doohan', 'dooha_jack7@gmail.com', ''),
('Theo Pourchaire', 'pourd_theo5@gmail.com', ''),
('Callum Ilott', 'ilott_call12@gmail.com', ''),
('Robert Kubica', 'kubic_robe88@gmail.com', '');