INSERT INTO `users` (`name`, `email`, `password_hash`, `first_login`) VALUES
('Christian Horner', 'horne_chri87@gmail.com', '$2b$10$rUJjJ4x3NZ4T/CVbc5Bv8.r7zHdCN/BIxp8WA/hk0aFqGjWHbrNMO', '0');

INSERT INTO `users` (`name`, `email`, `password_hash`) VALUES

('Toto Wolff', 'wolff_toto00@gmail.com', ''),
('James Vowles', 'vowle_jame00@gmail.com', ''),
('Zak Brown', 'brown_zak00@gmail.com', ''),

('Max Verstappen', 'verst_max1@gmail.com', ''),
('Sergio Perez', 'perez_serg11@gmail.com', ''),
('Lewis Hamilton', 'hamil_lewi44@gmail.com', ''),
('George Russell', 'russe_geor63@gmail.com', ''),
('Charles Leclerc', 'lecle_char16@gmail.com', ''),
('Carlos Sainz', 'sainz_carl55@gmail.com', ''),
('Lando Norris', 'norri_land4@gmail.com', ''),
('Oscar Piastri', 'piast_osca81@gmail.com', ''),
('Fernando Alonso', 'alons_fern14@gmail.com', ''),
('Lance Stroll', 'strol_lanc18@gmail.com', ''),
('Pierre Gasly', 'gasly_pierr10@gmail.com', ''),
('Esteban Ocon', 'ocon_este31@gmail.com', ''),
('Yuki Tsunoda', 'tsuno_yuki22@gmail.com', ''),
('Daniel Ricciardo', 'ricci_dani3@gmail.com', ''),
('Valtteri Bottas', 'botta_valt77@gmail.com', ''),
('Zhou Guanyu', 'zhou_guan24@gmail.com', ''),
('Kevin Magnussen', 'magnu_kevi20@gmail.com', ''),
('Nico Hulkenberg', 'hulke_nico27@gmail.com', ''),
('Alexander Albon', 'albon_alex23@gmail.com', ''),
('Logan Sargeant', 'sarge_loga2@gmail.com', ''),
('Nyck de Vries', 'devri_nyck21@gmail.com', ''),
('Liam Lawson', 'lawso_liam40@gmail.com', ''),
('Kimi Raikkonen', 'raikk_kimi7@gmail.com', ''),
('Sebastian Vettel', 'vette_seba5@gmail.com', ''),
('Jenson Button', 'butto_jens22@gmail.com', ''),
('Nico Rosberg', 'rosbe_nico6@gmail.com', ''),
('Felipe Massa', 'massa_feli19@gmail.com', ''),
('Rubens Barrichello', 'barri_rube11@gmail.com', ''),
('Michael Schumacher', 'schum_mich47@gmail.com', ''),
('Mick Schumacher', 'schum_mick47@gmail.com', ''),
('Romain Grosjean', 'grosj_roma8@gmail.com', ''),
('Pastor Maldonado', 'maldo_past18@gmail.com', ''),
('Ayrton Senna', 'senna_ayrt12@gmail.com', ''),
('Alain Prost', 'prost_alai1@gmail.com', ''),
('Niki Lauda', 'lauda_niki12@gmail.com', ''),
('Gerhard Berger', 'berge_gerh28@gmail.com', ''),
('David Coulthard', 'coult_davi2@gmail.com', ''),
('Mika Hakkinen', 'hakki_mika8@gmail.com', ''),
('Jacques Villeneuve', 'ville_jacq27@gmail.com', ''),
('Juan Pablo Montoya', 'monto_juan42@gmail.com', ''),
('Kimi Antonelli', 'anton_kimi12@gmail.com', ''),
('Oliver Bearman', 'bearm_oliv87@gmail.com', ''),
('Jack Doohan', 'dooha_jack7@gmail.com', ''),
('Theo Pourchaire', 'pourd_theo5@gmail.com', ''),
('Callum Ilott', 'ilott_call12@gmail.com', ''),
('Robert Kubica', 'kubic_robe88@gmail.com', ''),

('Billy Butcher', 'butch_bill17@gmail.com', ''),
('Hughie Campbell', 'campb_hugh18@gmail.com', ''),
('Annie January', 'janua_anni19@gmail.com', ''),
('John Homelander', 'homel_john20@gmail.com', ''),
('Maggie Maeve', 'maeve_magg21@gmail.com', ''),
('Kimiko Miyashiro', 'miyas_kimi22@gmail.com', ''),
('Serge Frenchie', 'frenc_serg23@gmail.com', ''),
('Marvin Milk', 'milk_marv24@gmail.com', ''),
('Ben Soldier', 'soldi_ben25@gmail.com', ''),
('Victoria Neuman', 'neuma_vict26@gmail.com', ''),
('Ashley Barrett', 'barre_ashl27@gmail.com', ''),
('Reggie Franklin', 'frank_regg28@gmail.com', ''),
('Earving Noir', 'noir_earv29@gmail.com', ''),
('Kevin Moskowitz', 'mosko_kevi30@gmail.com', ''),
('Ryan Butcher', 'butch_ryan31@gmail.com', ''),
('Cindy Campbell', 'campb_cind32@gmail.com', ''),
('Brenda Meeks', 'meeks_bren33@gmail.com', ''),
('Shorty Meeks', 'meeks_shor34@gmail.com', ''),
('Ray Wilkins', 'wilki_ray35@gmail.com', ''),
('Bobby Prinze', 'prinz_bobb36@gmail.com', ''),
('Buffy Gilmore', 'gilmo_buff37@gmail.com', ''),
('Greg Phillippe', 'phill_greg38@gmail.com', ''),
('Doofy Gilmore', 'gilmo_doof39@gmail.com', ''),
('Gail Hailstorm', 'hails_gail40@gmail.com', ''),
('Dwight Hartman', 'hartm_dwig41@gmail.com', ''),
('Jane Hopper', 'hoppe_jane42@gmail.com', ''),
('Mike Wheeler', 'wheel_mike43@gmail.com', ''),
('Dustin Henderson', 'hende_dust44@gmail.com', ''),
('Lucas Sinclair', 'sincl_luca45@gmail.com', ''),
('Max Mayfield', 'mayfi_max46@gmail.com', ''),
('Will Byers', 'byers_will47@gmail.com', ''),
('Nancy Wheeler', 'wheel_nanc48@gmail.com', ''),
('Jonathan Byers', 'byers_jona49@gmail.com', ''),
('Steve Harrington', 'harri_stev50@gmail.com', ''),
('Robin Buckley', 'buckl_robi51@gmail.com', ''),
('Jim Hopper', 'hoppe_jim52@gmail.com', ''),
('Joyce Byers', 'byers_joyc53@gmail.com', ''),
('Eddie Munson', 'munso_eddi54@gmail.com', ''),
('Murray Bauman', 'bauma_murr55@gmail.com', ''),
('Erica Sinclair', 'sincl_eric56@gmail.com', ''),
('Wednesday Addams', 'addam_wedn57@gmail.com', ''),
('Enid Sinclair', 'sincl_enid58@gmail.com', ''),
('Bianca Barclay', 'barcl_bian59@gmail.com', ''),
('Xavier Thorpe', 'thorp_xavi60@gmail.com', ''),
('Tyler Galpin', 'galpi_tyle61@gmail.com', ''),
('Eugene Otinger', 'oting_euge62@gmail.com', ''),
('Morticia Addams', 'addam_mort63@gmail.com', ''),
('Gomez Addams', 'addam_gome64@gmail.com', ''),
('Pugsley Addams', 'addam_pugs65@gmail.com', ''),
('Larissa Weems', 'weems_lari66@gmail.com', ''),
('Joel Miller', 'mille_joel67@gmail.com', ''),
('Ellie Williams', 'willi_elli68@gmail.com', ''),
('Tommy Miller', 'mille_tomm69@gmail.com', ''),
('Sarah Miller', 'mille_sara70@gmail.com', ''),
('Tess Servopoulos', 'servo_tess71@gmail.com', ''),
('Marlene Stone', 'stone_marl72@gmail.com', ''),
('Bill Franklin', 'frank_bill73@gmail.com', ''),
('Frank Franklin', 'frank_fran74@gmail.com', ''),
('Abby Anderson', 'ander_abby75@gmail.com', ''),
('Dina Alvarez', 'alvar_dina76@gmail.com', ''),
('Rhaenyra Targaryen', 'targa_rhae77@gmail.com', ''),
('Daemon Targaryen', 'targa_daem78@gmail.com', ''),
('Alicent Hightower', 'hight_alic79@gmail.com', ''),
('Viserys Targaryen', 'targa_vise80@gmail.com', ''),
('Jacaerys Velaryon', 'velar_jaca81@gmail.com', ''),
('Lucerys Velaryon', 'velar_luce82@gmail.com', ''),
('Corlys Velaryon', 'velar_corl83@gmail.com', ''),
('Rhaenys Targaryen', 'targa_rhae84@gmail.com', ''),
('Aemond Targaryen', 'targa_aemo85@gmail.com', ''),
('Helaena Targaryen', 'targa_hela86@gmail.com', ''),
('Carmen Berzatto', 'berza_carm87@gmail.com', ''),
('Sydney Adamu', 'adamu_sydn88@gmail.com', ''),
('Richard Jerimovich', 'jerim_rich89@gmail.com', ''),
('Natalie Berzatto', 'berza_nata90@gmail.com', ''),
('Marcus Brooks', 'brook_marc91@gmail.com', ''),
('Tina Marrero', 'marre_tina92@gmail.com', ''),
('Ebraheim Hassan', 'hassa_ebra93@gmail.com', ''),
('Neil Fak', 'fak_neil94@gmail.com', ''),
('Claire Dunlap', 'dunla_clai95@gmail.com', ''),
('Michael Berzatto', 'berza_mich96@gmail.com', ''),
('Barbie Roberts', 'rober_barb97@gmail.com', ''),
('Ken Carson', 'carso_ken98@gmail.com', ''),
('Gloria Rivera', 'river_glor99@gmail.com', ''),
('Sasha Rivera', 'river_sash100@gmail.com', ''),
('Weird Barbie', 'barbi_weir101@gmail.com', ''),
('Allan Sherwood', 'sherw_alla102@gmail.com', ''),
('President Barbie', 'barbi_pres103@gmail.com', ''),
('Midge Hadley', 'hadle_midg104@gmail.com', ''),
('Ruth Handler', 'handl_ruth105@gmail.com', ''),
('Skipper Roberts', 'rober_skip106@gmail.com', ''),
('Lucy MacLean', 'macle_lucy107@gmail.com', ''),
('Maximus Stone', 'stone_maxi108@gmail.com', ''),
('Cooper Howard', 'howar_coop109@gmail.com', ''),
('Norm MacLean', 'macle_norm110@gmail.com', ''),
('Hank MacLean', 'macle_hank111@gmail.com', ''),
('Lee Moldaver', 'molda_lee112@gmail.com', ''),
('Thaddeus Brown', 'brown_thad113@gmail.com', ''),
('Dane Murphy', 'murph_dane114@gmail.com', ''),
('Betty Pearson', 'pears_bett115@gmail.com', ''),
('Ma June', 'june_ma116@gmail.com', '');

UPDATE `users`
SET `password_hash` = '$2b$10$scOpoH38xciwzF5EVUE9y.yuDDOqYK7xDibgPMdX..EOWSAOmB53m',
    `first_login` = '0'
WHERE `email` = 'horne_chri87@gmail.com';

UPDATE `users`
SET `password_hash` = '$2b$10$dRZu.GhSJFg2g9AitFqmD.Ncpr9VzrtMVZuVYSfR8KnhbXGzS5ixa',
    `first_login` = '1'
WHERE `email` = 'wolff_toto00@gmail.com';

UPDATE `users`
SET `password_hash` = '$2b$10$QFc58ZmTD31v82f29489jekSxQBu0ZgTonJiy3x//n6JtB17dKNiC',
    `first_login` = '1'
WHERE `email` = 'vowle_jame00@gmail.com';

UPDATE `users`
SET `password_hash` = '$2b$10$/HWKBBWGWstjhHn3kzWZduG9oFicZ2TxUTRt73tTWrY48ISelH1Ei',
    `first_login` = '1'
WHERE `email` = 'brown_zak00@gmail.com';

UPDATE `users`
SET `password_hash` = '$2b$10$qQjS4hNDGisYTg77DV/zyeuY3DquXTCTtN8N.W17Os2AL9gorQN/q',
    `first_login` = '1'
WHERE `email` = 'barre_ashl27@gmail.com';
